### ISSUE TITLE
Networking documentation needs updated

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#1517]
As I was setting up an instance of CAPE for the first time in a long time, I noticed a few places where the networking documentation could be improved. Rather than opening up a bunch of small PRs or one big PR, I figured it would be better to document them all in this issue to the project maintainers can look at this advice and adapt it as they see fit.

## Default configuration of the path to tcpdump is incorrect

At least in Ubuntu 22.04 LTS, `tcpdump` is located at `/usr/bin/tcpdump`, not `/usr/sbin/tcpdump`.

## instructions for "dirty line" internet connection are outdated

The current [Per-Analysis Network Routing](https://capev2.readthedocs.io/en/latest/installation/host/routing.html) documentation for an internet "dirty line" states to add an entry to `/etc/iproute2/rt_tables`. In modern releases of Ubuntu, all network configuration is handled by `netplan`, including routing tables.

First, disable `cloud-init`, which is used by Ubuntu Server by default.

Do this by writing a file at `/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg`, with the content `{config: disabled}`, then delete `/etc/netplan/50-cloud-init.yaml`.

If, for some reason you are using a desktop version of Ubuntu instead, you will need to disable `NetworkManager` and enable `networkd`.

```text
sudo systemctl stop NetworkManager
sudo systemctl disable NetworkManager
sudo systemctl mask NetworkManager
sudo rm /etc/netplan/01-network-manager-all.yaml

sudo systemctl unmask systemd-networkd
sudo systemctl enable systemd-networkd
sudo systemctl start systemd-networkd
```

Next, create your own `netplan` configuration file manually at `/etc/netplan/99-manual.yaml`

For example, here is my `netplan` configuration, which has a 5G hotspot connected via USB as the default gateway, and a management interface for hosting SSH and the CAPE web interface on an isolated VLAN.

```yaml
network:
    version: 2
    renderer: networkd
    ethernets:
        lo:
            addresses: [ "127.0.0.1/8", "::1/128", "7.7.7.7/32" ]
        enx00a0c6000000:
            dhcp4: no
            addresses: [ "192.168.1.2/24" ]
            nameservers:
                addresses: [ "192.168.1.1" ]
            routes:
                - to: default
                  via: 192.168.1.1
                - to: 192.168.1.0/24
                  via: 192.168.1.1
                  table: 101
            routing-policy:
             - from: 192.168.1.0/24
               table: 101
        enp8s0:
            dhcp4: no
            addresses: [ "10.23.6.66/24" ]
            routes:
                - to: 10.23.6.0/24
                  via: 10.23.6.1
                  table: 102
            routing-policy:
                - from: 10.23.6.0/24
                  table: 102
```

## Windows DNS server settings are inaccurate or incomplete

The screenshot of the Windows IPv4 configuration setting shows the primary DNS server set to the IP address of the host interface. In my testing this does not work when an internet or VPN route is used. A public DNS resolver such as Cloudflare's `1.1.1.1` and `1.0.0.1` or Google's `8.8.8.8` and `4.4.4.4` must be used instead.

Is there a better way to to this? Having a static IP manually set in Windows and/or DNS manually set to known public resolvers would be a good antisandboxing check for malware.

Libvirt does support setting a static IP via DHCP in as a `host` XML element, but I don't think there's a way to set custom DNS servers that way. Upstream DNS servers could be added to the configuration of the `libvirt` instance of `dnsmasq`, but that could cause DNS leaks.

## Updating trusted root certificates

Ideally, a Windows sandbox VM should be created, activated, and configured without ever connecting to the internet. However, this means that trusted root certificates are not updated, which leads to certificate warnings when trying to access  many HTTPS//TLS servers.

The trusted root certificates can be updated manually by exporting the certificates from Windows Update on a non-isolated system and importing them in the sandbox VM.

Export the certificates.

```powershell
certutil.exe –generateSSTFromWU roots.sst
```

Copy `roots.sst` to the sandbox VM, then import the certificates in PowerShell as Administrator.

```powershell
Import-Certificate roots.sst -CertStoreLocation Cert:\LocalMachine\Root
```

## Missing documentation on how tlsdump works

How does `tcpdump` work? What are its limitations?
